import { ApolloWrapper } from "./ApolloWrapper";
import { AuthProvider } from './auth';
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <AuthProvider>
        <ApolloWrapper>
          <body>
            {children}
          </body>
        </ApolloWrapper>
      </AuthProvider>
    </html>
  );
}
